version: '3'

services:
  wisdom-server:
    build:
      context: .
      dockerfile: cmd/server/Dockerfile
    ports:
      - "8080:8080"

  wisdom-client:
    build:
      context: .
      dockerfile: cmd/client/Dockerfile
    depends_on:
      - wisdom-server
    environment:
      - SERVER_URL=wisdom-server:8080
